# Project information
site_name: DART Documentation
repo_url: https://github.com/dartsim/dart.git
repo_name: GitHub
site_description: Dynamic Animation and Robotics Toolkit
# site_favicon: null  # todo: add dart.ico
copyright: ﻿Copyright (c) 2011-2015, Georgia Tech Research Corporation

# Build directories
theme: readthedocs
docs_dir: docs/readthedocs

# Extentions
markdown_extensions: [math]
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

pages:
- Home: 'index.md'
- Tutorials:
    - 'Introduction': 'tutorials/introduction.md'
    - 'Pendulum': 'tutorials/multi-pendulum.md'
    - 'Collisions' : 'tutorials/collisions.md'
    - 'Manipulator': 'tutorials/dominoes.md'
    - 'Biped': 'tutorials/biped.md'
